# Generated by Django 2.1.7 on 2020-03-15 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='projects.Task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.ProjectCategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(related_name='participating_projects', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='taskfileteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_file_teams', to='projects.Team'),
        ),
        migrations.AlterField(
            model_name='taskoffer',
            name='offerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_offers', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='taskoffer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='projects.Task'),
        ),
    ]
