# Generated by Django 3.0.4 on 2020-04-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectcategoryproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('a', 'Accepted'), ('p', 'Pending'), ('d', 'Declined')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('o', 'Open'), ('i', 'In progress'), ('f', 'Finished')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ad', 'Waiting for delivery'), ('pa', 'Delivered and waiting for acceptance'), ('pp', 'Delivery has been accepted, awaiting payment'), ('ps', 'Payment for delivery is done'), ('dd', 'Declined delivery, please revise')], default='ad', max_length=2),
        ),
        migrations.AlterField(
            model_name='taskoffer',
            name='status',
            field=models.CharField(choices=[('a', 'Accepted'), ('p', 'Pending'), ('d', 'Declined')], default='p', max_length=1),
        ),
    ]
