coverage:
  status:
    project:
      default:
        threshold: 80%
    patch:
      default:
        threshold: 80%
  ignore:
    - manage.py
    - agreelance/wsgi.py
    - agreelance/**settings**.py
    - **/apps.py
    - **/test*.py
    - **/*test.py
    - **/migrations/*
    - **/__init__.py
