# Generated by Django 2.1.7 on 2020-03-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200116_1130'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='categories',
            new_name='competence_categories',
        ),
    ]
