# Generated by Django 2.1.7 on 2020-03-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_profile_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='competence_categories',
            field=models.ManyToManyField(related_name='competent_profiles', to='projects.ProjectCategory'),
        ),
    ]
